# Generated by Django 5.1.4 on 2025-02-27 15:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_conversation_user"),
        ("userapp", "0004_user_last_login_date_user_last_login_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_text", models.TextField(verbose_name="User Input")),
                (
                    "prediction_result",
                    models.CharField(max_length=100, verbose_name="Prediction Result"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Prediction Time",
                    ),
                ),
                (
                    "music_therapy_links",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Music Therapy Links"
                    ),
                ),
                (
                    "guided_workout_plan",
                    models.TextField(blank=True, verbose_name="Guided Workout Plan"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="userapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "user_predictions",
            },
        ),
    ]
