# Generated by Django 5.1.4 on 2025-02-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserFeedback",
        ),
    ]
