# Generated by Django 5.1.4 on 2025-02-27 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0002_delete_userfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Review", models.CharField(max_length=1000)),
                ("Rating", models.CharField(max_length=1000)),
                ("Sentiment", models.CharField(max_length=1000)),
                ("Feedback_Time", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="userapp.user"
                    ),
                ),
            ],
            options={
                "db_table": "user_feedback",
            },
        ),
    ]
