# Generated by Django 5.1.4 on 2025-02-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0003_feedbackmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="Last_Login_Date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="Last_Login_Time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="No_Of_Times_Login",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
